
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import Header from "./Nav/Header";
import 'bootstrap/dist/css/bootstrap.min.css';
import Category from "./category/page";
import Footer from "./Footer/Footer";
import Providers from "./Redux/Providers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AV App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
         {/* ✅ Bootstrap JS loads only on browser, never server */}
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
          strategy="beforeInteractive"
        />

        <Providers>
          <Header />
          <Category />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
