
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./Nav/page";
import 'bootstrap/dist/css/bootstrap.min.css';
import Category from "./category/page";
import Footer from "./Footer/Footer";
import Providers from "./Redux/Providers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AV App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <Providers>
          <Header />
          <Category />
          {children}
          <Footer/>
          </Providers>
      </body>
    </html>
  );
}
